services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:6.0
    container_name: rastreapp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: rastreapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rastreapp-network

  # MongoDB Express (opcional - interfaz web para MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: rastreapp-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - rastreapp-network

  # Servidor backend
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rastreapp-server
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/rastreapp?authSource=admin
      PORT: 3001
      API_BASE_URL: http://localhost:3001/api
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - rastreapp-network
    volumes:
      - ./server:/app/server
      - /app/node_modules

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rastreapp-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - rastreapp-network

volumes:
  mongodb_data:
    driver: local

networks:
  rastreapp-network:
    driver: bridge
